# Generated by Django 4.0.4 on 2022-05-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='admin', max_length=200),
        ),
    ]
