# Generated by Django 4.0.4 on 2022-05-23 23:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 23, 23, 17, 7, 810285, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
