# Generated by Django 4.0.4 on 2022-05-25 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0010_order_payment_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_completed',
        ),
    ]
