# Generated by Django 4.0.4 on 2022-05-26 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0001_initial'),
        ('ecomapp', '0014_remove_customer_user_alter_cart_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecomadmin.admin'),
        ),
    ]
